# Generated by Django 5.2.13 on 2026-05-01 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GorevGrubu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('aktivite_tipi', models.CharField(blank=True, choices=[('konu_anlatimi', 'Konu Anlatımı'), ('soru_cozumu', 'Soru Çözümü'), ('tekrar', 'Tekrar')], max_length=32, null=True)),
                ('ozel_sure_dk', models.IntegerField(blank=True, null=True)),
                ('ders_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sira_no', models.IntegerField(default=0)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tarih', 'sira_no'],
            },
        ),
        migrations.CreateModel(
            name='GrupDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('sure_bilgisi', models.CharField(blank=True, max_length=64, null=True)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='kocluk.gorevgrubu')),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=200)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('koc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenciler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='KaynakKitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitap_adi', models.CharField(max_length=255)),
                ('ders', models.CharField(max_length=64)),
                ('sinav_tipi', models.CharField(max_length=32)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaynak_kitaplar', to='kocluk.ogrenci')),
            ],
            options={
                'ordering': ['kitap_adi'],
            },
        ),
        migrations.AddField(
            model_name='gorevgrubu',
            name='ogrenci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorev_gruplari', to='kocluk.ogrenci'),
        ),
        migrations.AddConstraint(
            model_name='ogrenci',
            constraint=models.UniqueConstraint(fields=('koc', 'ad_soyad'), name='uniq_koc_ad_soyad'),
        ),
        migrations.AddConstraint(
            model_name='kaynakkitap',
            constraint=models.UniqueConstraint(fields=('ogrenci', 'kitap_adi', 'ders', 'sinav_tipi'), name='uniq_kaynak_per_ogrenci'),
        ),
        migrations.AddIndex(
            model_name='gorevgrubu',
            index=models.Index(fields=['ogrenci', 'tarih'], name='kocluk_gore_ogrenci_733fa9_idx'),
        ),
    ]
