# Generated by Django 5.2.13 on 2026-05-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kocluk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorevgrubu',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
