# Generated by Django 5.2.13 on 2026-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_user_is_approved_studentinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='denemeler_v2',
            field=models.BooleanField(default=False),
        ),
    ]
