# Generated by Django 5.2.13 on 2026-05-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_user_denemeler_v2_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('auto', 'Otomatik'), ('light', 'Açık'), ('dark', 'Koyu')], default='auto', max_length=10),
        ),
    ]
