# Generated by Django 5.2.13 on 2026-05-14 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_add_theme_and_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Koç Erişim Kaydı',
                'verbose_name_plural': 'Koç Erişim Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CoachStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_student_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_coach_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Koç-Öğrenci İlişkisi',
                'verbose_name_plural': 'Koç-Öğrenci İlişkileri',
                'unique_together': {('coach', 'student')},
            },
        ),
    ]
