# Generated by Django 5.2.13 on 2026-05-14 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_add_coach_student_and_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, choices=[('mat', 'Matematik'), ('tur', 'Türkçe'), ('sos', 'Sosyal'), ('fen', 'Fen')], max_length=10)),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_tasks_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_tasks_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Koç Görevi',
                'verbose_name_plural': 'Koç Görevleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateCoachNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='private_notes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_private_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Özel Koç Notu',
                'verbose_name_plural': 'Özel Koç Notları',
                'ordering': ['-created_at'],
            },
        ),
    ]
