# Generated by Django 5.2.13 on 2026-05-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_add_coach_task_and_private_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatecoachnote',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='privatecoachnote',
            name='student',
        ),
        migrations.DeleteModel(
            name='CoachTask',
        ),
        migrations.DeleteModel(
            name='PrivateCoachNote',
        ),
    ]
