# Generated by Django 5.2.13 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_remove_coach_task_and_private_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brans_v2',
            field=models.BooleanField(default=False),
        ),
    ]
