# Generated by Django 5.2.13 on 2026-05-17 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_user_brans_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('exam_stagnation', 'Sınav Durağanlığı'), ('net_decline', 'Net Düşüşü'), ('net_momentum', 'Net Artışı'), ('task_neglect', 'Görev İhmali'), ('radar_overload', 'Radar Birikimi')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Kritik'), ('warning', 'Uyarı'), ('positive', 'Olumlu')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Koç Uyarısı',
                'verbose_name_plural': 'Koç Uyarıları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coach', 'is_dismissed', 'is_read'], name='users_app_c_coach_i_8ec68e_idx')],
                'unique_together': {('coach', 'student', 'fingerprint')},
            },
        ),
    ]
