# Generated by Django 5.2.13 on 2026-05-18 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_coach_alert_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_key', models.CharField(choices=[('streak_3', '3 Günlük Seri'), ('streak_7', '7 Günlük Seri'), ('streak_14', '14 Günlük Seri'), ('streak_30', '30 Günlük Seri'), ('streak_60', '60 Günlük Seri'), ('streak_100', '100 Günlük Seri'), ('exam_1', 'İlk Sınav'), ('exam_10', '10 Sınav'), ('exam_25', '25 Sınav'), ('exam_50', '50 Sınav'), ('task_10', '10 Görev'), ('task_50', '50 Görev'), ('comeback', 'Yeniden Başladı'), ('perfect_week', 'Mükemmel Hafta')], db_index=True, max_length=20)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Başarı Rozeti',
                'verbose_name_plural': 'Başarı Rozetleri',
                'ordering': ['-awarded_at'],
                'unique_together': {('student', 'badge_key')},
            },
        ),
    ]
