# Generated by Django 5.2.13 on 2026-05-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0012_remove_user_brans_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ayt_target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tyt_target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
