# Generated by Django 5.2.13 on 2026-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0013_user_target_exam_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alan',
            field=models.CharField(blank=True, choices=[('SAY', 'SAY'), ('EA', 'EA'), ('SOZ', 'SÖZ'), ('DIL', 'DİL')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='sinif',
            field=models.CharField(blank=True, choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('mezun', 'Mezun')], default='', max_length=5),
        ),
    ]
