# Generated by Django 5.2.13 on 2026-09-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0022_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wordpress_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wp_is_available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
