# Generated by Django 5.2.13 on 2026-09-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0023_add_wordpress_post_id_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachstudent',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Koç tarafından kaldırıldı'), ('payment_overdue', 'Ödeme gecikmesi')], max_length=20, null=True),
        ),
    ]
