# Generated by Django 5.2.13 on 2026-09-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konu_takip_app', '0003_studentsubjectsrsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubjectsrsetting',
            name='sr_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
