# Generated by Django 5.2.13 on 2026-05-27 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('student', 'Öğrenciler için'), ('parent', 'Veliler için')], default='student', max_length=10)),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SSS',
                'verbose_name_plural': 'SSS (Sıkça Sorulan Sorular)',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(help_text='Kısa açıklama (ana sayfa kartı)', max_length=240)),
                ('body', models.TextField(blank=True, help_text='Uzun açıklama (özellikler sayfası)')),
                ('icon_svg', models.TextField(blank=True, help_text='Inline SVG markup (viewBox 0 0 20 20 ölçüsünde)')),
                ('accent', models.CharField(choices=[('indigo', 'İndigo'), ('violet', 'Mor'), ('emerald', 'Zümrüt')], default='indigo', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Özellik Kartı',
                'verbose_name_plural': 'Özellik Kartları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('badge_label', models.CharField(blank=True, help_text='Örn: ★ En Çok Tercih Edilen', max_length=60)),
                ('is_featured', models.BooleanField(default=False, help_text='Öne çıkan plan (primary buton stilini alır)')),
                ('price_monthly_try', models.PositiveIntegerField(help_text='Aylık TL fiyatı')),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('summary', models.CharField(blank=True, help_text='Örn: Toplam ₺594 — 1 ay hediye · %33 indirim', max_length=160)),
                ('cta_label', models.CharField(default='14 Gün Ücretsiz Başla', max_length=60)),
                ('cta_url', models.CharField(default='/auth/register/', max_length=200)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fiyat Planı',
                'verbose_name_plural': 'Fiyat Planları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='YKS 2027 · Akıllı çalışma platformu', max_length=120)),
                ('hero_title_line1', models.CharField(default='YKS hazırlığını', max_length=120)),
                ('hero_title_line2', models.CharField(default='plansız bırakma.', max_length=120)),
                ('hero_subtitle', models.TextField(default='Vagus; deneme analizlerini, konu eksiklerini, haftalık görevlerini ve TYT/AYT yol haritanı tek panelde takip etmeni sağlar. Ne çalışacağını, ne zaman çalışacağını ve nasıl geliştiğini net gör.')),
                ('hero_cta_primary_label', models.CharField(default='Hemen Başla', max_length=60)),
                ('hero_cta_primary_url', models.CharField(default='/auth/register/', max_length=200)),
                ('hero_cta_secondary_label', models.CharField(default='Demo İncele', max_length=60)),
                ('hero_cta_secondary_url', models.CharField(default='/ozellikler/', max_length=200)),
                ('final_cta_title', models.CharField(default='YKS sürecini bugün düzene koy.', max_length=160)),
                ('final_cta_subtitle', models.CharField(default='14 gün ücretsiz. Kredi kartı gerekmez. Kayıt 60 saniye.', max_length=240)),
                ('nav_cta_label', models.CharField(default='Hemen Başla', max_length=60)),
                ('nav_cta_url', models.CharField(default='/auth/register/', max_length=200)),
                ('footer_tagline', models.TextField(default='YKS hazırlığında ne çalışacağını, ne zaman çalışacağını ve nasıl geliştiğini net gösteren akıllı çalışma platformu.')),
                ('footer_copyright', models.CharField(default='© 2026 Vagus. Tüm hakları saklıdır.', max_length=100)),
                ('footer_location', models.CharField(default='Ankara · Türkiye', max_length=60)),
                ('contact_email', models.EmailField(default='hello@vagus.app', max_length=254)),
                ('contact_corporate_email', models.EmailField(default='kurumsal@vagus.app', max_length=254)),
                ('contact_whatsapp', models.CharField(default='+90 532 444 55 66', max_length=30)),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('student_name', models.CharField(max_length=60)),
                ('initials', models.CharField(max_length=2)),
                ('accent', models.CharField(choices=[('violet-indigo', 'Mor-İndigo'), ('emerald', 'Zümrüt'), ('amber', 'Kehribar')], default='violet-indigo', max_length=20)),
                ('quote', models.TextField()),
                ('student_info', models.CharField(blank=True, help_text='Örn: 12. Sınıf · Sayısal · İstanbul', max_length=120)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Öğrenci Görüşü',
                'verbose_name_plural': 'Öğrenci Görüşleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Boş bırakılırsa kullanıcı adı kullanılır', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Örn: Matematik Koçu', max_length=120)),
                ('specialty', models.CharField(blank=True, help_text='Örn: Sayısal · AYT Matematik', max_length=200)),
                ('bio_short', models.CharField(blank=True, help_text='Liste kartında gösterilen kısa bio', max_length=200)),
                ('bio_long', models.TextField(blank=True, help_text='Profil detay sayfasında gösterilen uzun bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coaches/')),
                ('accent', models.CharField(choices=[('indigo', 'İndigo'), ('violet', 'Mor'), ('emerald', 'Zümrüt'), ('amber', 'Kehribar')], default='indigo', help_text='Fotoğraf yoksa kullanılacak avatar rengi', max_length=10)),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Yıl olarak deneyim', null=True)),
                ('student_count', models.PositiveIntegerField(blank=True, help_text='Örn: 120 → "120+ öğrenci"', null=True)),
                ('success_metric', models.CharField(blank=True, help_text='Örn: Ortalama +12 net artışı', max_length=120)),
                ('is_public', models.BooleanField(default=False, help_text='İşaretlenirse koç /koclar/ sayfasında görünür')),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Koç Profili (Genel Site)',
                'verbose_name_plural': 'Koç Profilleri (Genel Site)',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=200)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='marketing_app.pricingplan')),
            ],
            options={
                'verbose_name': 'Plan Özelliği',
                'verbose_name_plural': 'Plan Özellikleri',
                'ordering': ['order'],
            },
        ),
    ]
