# Generated by Django 5.2.13 on 2026-05-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GorevGrubu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('aktivite_tipi', models.CharField(blank=True, choices=[('konu_anlatimi', 'Konu Anlatımı'), ('soru_cozumu', 'Soru Çözümü'), ('tekrar', 'Tekrar')], max_length=32, null=True)),
                ('ozel_sure_dk', models.IntegerField(blank=True, null=True)),
                ('ders_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sira_no', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='gorev_gruplari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Görev Grubu',
                'verbose_name_plural': 'Görev Grupları',
                'ordering': ['tarih', 'sira_no'],
            },
        ),
        migrations.CreateModel(
            name='GrupDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('sure_bilgisi', models.CharField(blank=True, max_length=64, null=True)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='tasks_app.gorevgrubu')),
            ],
            options={
                'verbose_name': 'Grup Detayı',
                'verbose_name_plural': 'Grup Detayları',
            },
        ),
        migrations.CreateModel(
            name='KaynakKitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitap_adi', models.CharField(max_length=255)),
                ('ders', models.CharField(max_length=64)),
                ('sinav_tipi', models.CharField(max_length=32)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='kaynak_kitaplar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kaynak Kitap',
                'verbose_name_plural': 'Kaynak Kitaplar',
                'ordering': ['kitap_adi'],
            },
        ),
        migrations.AddIndex(
            model_name='gorevgrubu',
            index=models.Index(fields=['student', 'tarih'], name='tasks_app_g_student_2e3320_idx'),
        ),
        migrations.AddConstraint(
            model_name='kaynakkitap',
            constraint=models.UniqueConstraint(fields=('student', 'kitap_adi', 'ders', 'sinav_tipi'), name='uniq_kaynak_per_student'),
        ),
    ]
