# Generated by Django 5.2.13 on 2026-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorevgrubu',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gorevgrubu',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gorevgrubu',
            name='tekrar_quality',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
