# Generated by Django 5.2.13 on 2026-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_gorevgrubu_completed_at_gorevgrubu_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorevgrubu',
            name='student_can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
