# Generated by Django 5.2.13 on 2026-05-04 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_gorevgrubu_student_can_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorevgrubu',
            name='is_master',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gorevgrubu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_copies', to='tasks_app.gorevgrubu'),
        ),
    ]
