# Generated by Django 5.2.13 on 2026-05-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0004_gorevgrubu_is_master_gorevgrubu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorevgrubu',
            name='is_hidden_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
