# Generated by Django 5.2.13 on 2026-05-26 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0018_topic_order_index'),
        ('tasks_app', '0005_gorevgrubu_is_hidden_by_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('channel_title', models.CharField(blank=True, max_length=255)),
                ('exam_type', models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT')], default='TYT', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_playlists', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_playlists', to='exams_app.subject')),
            ],
            options={
                'verbose_name': 'YouTube Playlist',
                'verbose_name_plural': 'YouTube Playlistler',
                'ordering': ['exam_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=300)),
                ('duration_min', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tasks_app.youtubeplaylist')),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videolar',
                'ordering': ['position'],
                'unique_together': {('playlist', 'video_id')},
            },
        ),
    ]
