# Generated by Django 5.2.13 on 2026-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0006_youtubeplaylist_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorevgrubu',
            name='student_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gorevgrubu',
            name='time_spent_dk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
