# Generated by Django 5.2.13 on 2026-09-20 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams_app', '0024_tyt_problemler_data'),
        ('konu_takip_app', '0004_sr_default_opt_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStruggleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.ImageField(upload_to='struggle/questions/%Y/%m/')),
                ('solution_image', models.ImageField(blank=True, null=True, upload_to='struggle/solutions/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('current_interval_days', models.PositiveIntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='struggle_questions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='struggle_questions', to='exams_app.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='struggle_questions', to='konu_takip_app.konutakiptopic')),
            ],
            options={
                'verbose_name': 'Zorlandığım Soru',
                'verbose_name_plural': 'Zorlandığım Sorular',
                'ordering': ['-created_at'],
            },
        ),
    ]
