# Generated by Django 5.2.13 on 2026-09-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struggle_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstrugglequestion',
            name='question_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentstrugglequestion',
            name='solution_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentstrugglequestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='struggle/questions/%Y/%m/'),
        ),
    ]
