from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from core_config.views import app_root_view, healthz_view
from exams_app.views import brans_hub_student, brans_hub_api, brans_subject_detail_student, brans_subject_detail_student_api, brans_hub_export, brans_subject_export
from users_app.views import profil_view, theme_save, activity_calendar_api, alan_sinif_save, profil_ayarlar, geri_bildirim_gonder, push_subscribe, push_unsubscribe, push_test, student_notifications_api, student_notification_read, student_notification_mark_all_read, coach_billing_view, panel_billing_view, panel_billing_update, panel_odemeler_view, panel_davetler_view, panel_ogrenciler_view, panel_student_unlink, panel_fee_tier_add, panel_fee_tier_update, panel_fee_tier_delete, panel_wp_koclar_view, panel_wp_koclar_confirm, panel_wp_koclar_unlink, profil_wp_availability

urlpatterns = [
    path('healthz/', healthz_view, name='healthz'),
    path('manifest.webmanifest',
         TemplateView.as_view(template_name='pwa/manifest.webmanifest',
                              content_type='application/manifest+json'),
         name='manifest'),
    path('service-worker.js',
         TemplateView.as_view(template_name='pwa/service-worker.js',
                              content_type='application/javascript'),
         name='service_worker'),
    path('offline/',
         TemplateView.as_view(template_name='pwa/offline.html'),
         name='offline'),

    path('admin/', admin.site.urls),
    path('', app_root_view, name='app_root'),
    path('', include('marketing_app.urls', namespace='marketing')),
    path('auth/', include('users_app.urls', namespace='users_app')),
    path('student/', include('exams_app.student_urls', namespace='student')),
    path('coach/', include('exams_app.coach_urls', namespace='coach')),
    path('coach/tasks/', include('tasks_app.urls', namespace='tasks')),
    path('student/tasks/', include('tasks_app.student_urls', namespace='student_tasks')),
    path('coach/konu-takip/', include('konu_takip_app.urls', namespace='konu_takip')),
    path('student/konu-takip/', include('konu_takip_app.student_urls', namespace='student_konu_takip')),
    path('brans/', brans_hub_student, name='brans_hub'),
    path('brans/api/', brans_hub_api, name='brans_hub_api'),
    path('brans/report/', brans_hub_export, name='brans_hub_export'),
    path('brans/<slug:subject_slug>/report/', brans_subject_export, name='brans_subject_export'),
    path('brans/<slug:subject_slug>/', brans_subject_detail_student, name='brans_subject_detail'),
    path('brans/<slug:subject_slug>/api/', brans_subject_detail_student_api, name='brans_subject_detail_api'),
    path('analiz/', RedirectView.as_view(pattern_name='brans_hub', permanent=True), name='analiz_redirect'),
    path('profil/', profil_view,    name='profil'),
    path('profil/theme/', theme_save, name='profil_theme'),
    path('profil/aktivite/', activity_calendar_api, name='profil_aktivite'),
    path('profil/alan-sinif/', alan_sinif_save, name='profil_alan_sinif'),
    path('profil/ayarlar/', profil_ayarlar, name='profil_ayarlar'),
    path('profil/geri-bildirim/', geri_bildirim_gonder, name='profil_geri_bildirim'),
    path('profil/push-subscribe/',   push_subscribe,   name='profil_push_subscribe'),
    path('profil/push-unsubscribe/', push_unsubscribe, name='profil_push_unsubscribe'),
    path('profil/push-test/',        push_test,        name='profil_push_test'),
    path('student/notifications/',              student_notifications_api,        name='student_notifications'),
    path('student/notifications/mark-all-read/', student_notification_mark_all_read, name='student_notifications_mark_all'),
    path('student/notifications/<int:pk>/read/', student_notification_read,          name='student_notification_read'),
    path('coach/odeme/', coach_billing_view, name='coach_billing'),
    path('panel/odeme/', panel_billing_view, name='panel_billing'),
    path('panel/odeme/<int:pk>/update/', panel_billing_update, name='panel_billing_update'),
    path('panel/odemeler/', panel_odemeler_view, name='panel_odemeler'),
    path('panel/davetler/', panel_davetler_view, name='panel_davetler'),
    path('panel/ogrenciler/', panel_ogrenciler_view, name='panel_ogrenciler'),
    path('panel/student/<int:coach_id>/<int:student_id>/unlink/', panel_student_unlink, name='panel_student_unlink'),
    path('panel/fee-tier/add/', panel_fee_tier_add, name='panel_fee_tier_add'),
    path('panel/fee-tier/<int:pk>/update/', panel_fee_tier_update, name='panel_fee_tier_update'),
    path('panel/fee-tier/<int:pk>/delete/', panel_fee_tier_delete, name='panel_fee_tier_delete'),
    path('panel/wp-koclar/', panel_wp_koclar_view, name='panel_wp_koclar'),
    path('panel/wp-koclar/confirm/', panel_wp_koclar_confirm, name='panel_wp_koclar_confirm'),
    path('panel/wp-koclar/<int:coach_id>/unlink/', panel_wp_koclar_unlink, name='panel_wp_koclar_unlink'),
    path('profil/wp-availability/', profil_wp_availability, name='profil_wp_availability'),
]
