# Generated by Django 5.2.13 on 2026-05-22 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams_app', '0013_alter_studenttask_next_review_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinav_tipi', models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT'), ('BOTH', 'TYT + AYT')], default='TYT', max_length=4)),
                ('target_date', models.DateField(help_text='Snapshot of the student exam date at plan creation time.')),
                ('algorithm', models.CharField(choices=[('even', 'Eşit Dağılım'), ('weighted_weakness', 'Zayıf Konulara Ağırlık')], default='even', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='macro_plans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='macro_plans_as_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Makro Plan',
                'verbose_name_plural': 'Makro Planlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MacroPlanBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('order', models.PositiveSmallIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='curriculum_app.macroplan')),
            ],
            options={
                'verbose_name': 'Plan Ayı',
                'verbose_name_plural': 'Plan Ayları',
                'ordering': ['order'],
                'unique_together': {('plan', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MacroPlanTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum_app.macroplanbucket')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_plan_entries', to='exams_app.topic')),
            ],
            options={
                'verbose_name': 'Plan Konusu',
                'verbose_name_plural': 'Plan Konuları',
                'ordering': ['order'],
                'unique_together': {('bucket', 'topic')},
            },
        ),
    ]
