# Generated by Django 5.2.13 on 2026-05-24 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='macroplan',
            name='segment',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='macroplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('APPROVED', 'Onaylandı')], db_index=True, default='DRAFT', max_length=10),
        ),
        migrations.CreateModel(
            name='PlanRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ahmet_syndrome', 'Ahmet Sendromu (TYT ihmalı)'), ('ea_verbal_delay', 'EA Sözel Gecikmesi'), ('baglayici_skipped', 'Bağlayıcı Konu Atlandı'), ('time_crunch', 'Yetersiz Süre'), ('overload', 'Aşırı Yük'), ('other', 'Diğer')], max_length=25)),
                ('severity', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('CRITICAL', 'Kritik')], default='WARNING', max_length=10)),
                ('message', models.TextField()),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='curriculum_app.macroplan')),
            ],
            options={
                'verbose_name': 'Risk Uyarısı',
                'verbose_name_plural': 'Risk Uyarıları',
                'ordering': ['-severity', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='MacroPlanWeekBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_index', models.PositiveSmallIntegerField()),
                ('pct_new_topic', models.PositiveSmallIntegerField(default=60, verbose_name='Yeni Konu %')),
                ('pct_revision', models.PositiveSmallIntegerField(default=25, verbose_name='Tekrar %')),
                ('pct_trial', models.PositiveSmallIntegerField(default=15, verbose_name='Deneme %')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='curriculum_app.macroplanbucket')),
            ],
            options={
                'verbose_name': 'Haftalık Dilim',
                'verbose_name_plural': 'Haftalık Dilimler',
                'ordering': ['bucket', 'week_index'],
                'unique_together': {('bucket', 'week_index')},
            },
        ),
        migrations.CreateModel(
            name='PlanningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(choices=[('tyt_ratio', 'TYT Oranı (0.0-1.0)'), ('yield_threshold', 'Düşük Verim Eşiği')], max_length=30)),
                ('value', models.CharField(help_text='Parsed by engine as float/int.', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='planning_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planlama Kuralı',
                'verbose_name_plural': 'Planlama Kuralları',
                'unique_together': {('coach', 'rule_key')},
            },
        ),
    ]
