# Generated by Django 5.2.13 on 2026-05-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_app', '0002_macroplan_segment_macroplan_status_planriskalert_and_more'),
        ('exams_app', '0015_split_umbrella_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroPlanWeekTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=3, verbose_name='Hedef Saat')),
                ('activity', models.CharField(choices=[('new', 'Yeni Konu'), ('revision', 'Tekrar'), ('repair', 'Zayıf Konu Onarımı'), ('trial', 'Deneme / Karışık')], db_index=True, default='new', max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_assignments', to='exams_app.topic')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum_app.macroplanweekbucket')),
            ],
            options={
                'verbose_name': 'Haftalık Konu Görevi',
                'verbose_name_plural': 'Haftalık Konu Görevleri',
                'ordering': ['week', 'order'],
                'unique_together': {('week', 'topic')},
            },
        ),
    ]
