# Generated by Django 5.2.13 on 2026-05-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_app', '0003_macroplanweektopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroplan',
            name='ayt_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macroplan',
            name='ayt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macroplan',
            name='planning_mode',
            field=models.CharField(choices=[('EXAM_DATE_BACKWARD', 'Sınav Tarihinden Geri Sayım'), ('CUSTOM_WINDOWS', 'Özel Tarih Aralıkları')], default='EXAM_DATE_BACKWARD', max_length=25),
        ),
        migrations.AddField(
            model_name='macroplan',
            name='tyt_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macroplan',
            name='tyt_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macroplanbucket',
            name='window_kind',
            field=models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT'), ('BOTH', 'TYT + AYT')], db_index=True, default='BOTH', max_length=4),
        ),
        migrations.AlterField(
            model_name='planriskalert',
            name='kind',
            field=models.CharField(choices=[('ahmet_syndrome', 'Ahmet Sendromu (TYT ihmali)'), ('ea_verbal_delay', 'EA Sozel Gecikmesi'), ('baglayici_skipped', 'Baglayici Konu Atlandi'), ('time_crunch', 'Yetersiz Sure'), ('overload', 'Asiri Yuk'), ('other', 'Diger')], max_length=25),
        ),
    ]
