# Generated by Django 5.2.13 on 2026-05-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_app', '0004_macroplan_ayt_end_date_macroplan_ayt_start_date_and_more'),
        ('exams_app', '0017_topic_excluded_from_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroplantopic',
            name='is_manual',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='MacroPlanSkippedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_topics', to='curriculum_app.macroplan')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_skips', to='exams_app.topic')),
            ],
            options={
                'verbose_name': 'Atlanan Konu',
                'verbose_name_plural': 'Atlanan Konular',
                'unique_together': {('plan', 'topic')},
            },
        ),
    ]
