# Generated by Django 5.2.13 on 2026-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deneme',
                'verbose_name_plural': 'Denemeler',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('wrong_answers', models.PositiveSmallIntegerField(default=0)),
                ('blank_answers', models.PositiveSmallIntegerField(default=0)),
                ('net_score', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Sonuç',
                'verbose_name_plural': 'Sonuçlar',
            },
        ),
        migrations.CreateModel(
            name='ExamTopicError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('wrong', 'Yanlış'), ('blank', 'Boş')], max_length=5)),
            ],
            options={
                'verbose_name': 'Konu Hatası',
                'verbose_name_plural': 'Konu Hataları',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Yayın',
                'verbose_name_plural': 'Yayınlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT')], default='TYT', max_length=3)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['exam_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
                'ordering': ['subject', 'name'],
            },
        ),
    ]
