# Generated by Django 5.2.13 on 2026-04-28 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams_app.exam'),
        ),
        migrations.AddField(
            model_name='examtopicerror',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_errors', to='exams_app.exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='exams_app.publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('exam_type', 'name')},
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='exams_app.subject'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='exams_app.subject'),
        ),
        migrations.AddField(
            model_name='examtopicerror',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='exams_app.topic'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['student', 'exam_date'], name='exams_app_e_student_e197df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'name')},
        ),
        migrations.AddIndex(
            model_name='examtopicerror',
            index=models.Index(fields=['exam', 'topic'], name='exams_app_e_exam_id_d66363_idx'),
        ),
    ]
