# Generated by Django 5.2.13 on 2026-04-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
