# Generated by Django 5.2.13 on 2026-04-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0003_add_question_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject', 'sub_category', 'name'], 'verbose_name': 'Konu', 'verbose_name_plural': 'Konular'},
        ),
        migrations.AlterUniqueTogether(
            name='examtopicerror',
            unique_together={('exam', 'topic')},
        ),
        migrations.AddField(
            model_name='examtopicerror',
            name='blank_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examtopicerror',
            name='wrong_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='examtopicerror',
            name='error_type',
        ),
    ]
