# Generated by Django 5.2.13 on 2026-04-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0004_restructure_topic_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='subject_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
