# Generated by Django 5.2.13 on 2026-04-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0006_exam_student_note_studenttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttask',
            name='assigned_by_coach',
            field=models.BooleanField(default=False),
        ),
    ]
