# Generated by Django 5.2.13 on 2026-04-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0007_alter_studenttask_assigned_by_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='easiness_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='interval_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='repetition_count',
            field=models.IntegerField(default=0),
        ),
    ]
