# Generated by Django 5.2.13 on 2026-05-05 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0008_studenttask_easiness_factor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BransDeneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('dogru', models.PositiveSmallIntegerField(default=0, verbose_name='Doğru')),
                ('yanlis', models.PositiveSmallIntegerField(default=0, verbose_name='Yanlış')),
                ('bos', models.PositiveSmallIntegerField(default=0, verbose_name='Boş')),
                ('net', models.FloatField(default=0, editable=False, verbose_name='Net')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brans_denemeler', to='exams_app.subject', verbose_name='Ders')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='brans_denemeler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branş Deneme',
                'verbose_name_plural': 'Branş Denemeler',
                'ordering': ['-tarih', '-olusturulma_tarihi'],
                'indexes': [models.Index(fields=['student', 'ders', 'tarih'], name='exams_app_b_student_e89845_idx')],
            },
        ),
    ]
