# Generated by Django 5.2.13 on 2026-05-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0009_bransdeneme'),
    ]

    operations = [
        migrations.AddField(
            model_name='bransdeneme',
            name='ogrenci_notu',
            field=models.TextField(blank=True, default='', verbose_name='Not'),
        ),
        migrations.AddField(
            model_name='bransdeneme',
            name='sure_dakika',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (dk)'),
        ),
    ]
