# Generated by Django 5.2.13 on 2026-05-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0010_bransdeneme_ogrenci_notu_bransdeneme_sure_dakika'),
    ]

    operations = [
        migrations.CreateModel(
            name='BransTopicError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yanlis_sayisi', models.PositiveSmallIntegerField(default=0, verbose_name='Yanlış Sayısı')),
                ('brans_deneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_errors', to='exams_app.bransdeneme')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brans_errors', to='exams_app.topic')),
            ],
            options={
                'verbose_name': 'Branş Konu Hatası',
                'verbose_name_plural': 'Branş Konu Hataları',
                'indexes': [models.Index(fields=['brans_deneme', 'topic'], name='exams_app_b_brans_d_5358ef_idx')],
                'unique_together': {('brans_deneme', 'topic')},
            },
        ),
    ]
