# Generated by Django 5.2.13 on 2026-05-16 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0011_branstopicerror'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenttask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='task_source',
            field=models.CharField(choices=[('trial', 'Trial'), ('branch', 'Branch')], db_index=True, default='trial', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='studenttask',
            unique_together={('student', 'topic', 'task_source')},
        ),
    ]
