# Generated by Django 5.2.13 on 2026-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0012_task_source_isolation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttask',
            name='next_review_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
