# Generated by Django 5.2.13 on 2026-05-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0013_alter_studenttask_next_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='exams_app.topic', verbose_name='Ön Koşul Konular'),
        ),
        migrations.AddField(
            model_name='topic',
            name='expected_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Beklenen Çalışma Saati'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_baglayici',
            field=models.BooleanField(default=False, verbose_name='Bağlayıcı Konu'),
        ),
        migrations.AddField(
            model_name='topic',
            name='priority_tag',
            field=models.CharField(choices=[('CORE', 'Temel (Zorunlu)'), ('INDEPENDENT', 'Bağımsız'), ('OPTIONAL', 'Opsiyonel')], default='CORE', max_length=12, verbose_name='Öncelik'),
        ),
        migrations.AddField(
            model_name='topic',
            name='yield_score',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Verim Skoru (0-100)'),
        ),
    ]
