# Generated by Django 5.2.13 on 2026-05-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0015_split_umbrella_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='excluded_from_planning',
            field=models.BooleanField(default=False),
        ),
    ]
