# Generated by Django 5.2.13 on 2026-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0016_subject_excluded_from_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='excluded_from_planning',
            field=models.BooleanField(default=False),
        ),
    ]
