# Generated by Django 5.2.13 on 2026-07-08 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0019_publisher_is_active_curated_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('duration_minutes', models.PositiveIntegerField(default=45, verbose_name='Süre (dk)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seviye Tespit Sınavı',
                'verbose_name_plural': 'Seviye Tespit Sınavları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Sıra')),
                ('question_text', models.TextField(verbose_name='Soru Metni')),
                ('question_image', models.URLField(blank=True, default='', verbose_name='Soru Görseli (URL)')),
                ('option_a', models.CharField(max_length=500, verbose_name='Seçenek A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Seçenek B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Seçenek C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Seçenek D')),
                ('option_e', models.CharField(max_length=500, verbose_name='Seçenek E')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Doğru Seçenek')),
                ('topic', models.CharField(blank=True, default='', max_length=200, verbose_name='Kazanım')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams_app.placementexam')),
            ],
            options={
                'verbose_name': 'Sınav Sorusu',
                'verbose_name_plural': 'Sınav Soruları',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('wrong_count', models.PositiveSmallIntegerField(default=0)),
                ('blank_count', models.PositiveSmallIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams_app.placementexam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğrenci Sınav Girişimi',
                'verbose_name_plural': 'Öğrenci Sınav Girişimleri',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams_app.studentexamattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams_app.examquestion')),
            ],
            options={
                'verbose_name': 'Öğrenci Cevabı',
                'verbose_name_plural': 'Öğrenci Cevapları',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
