# Generated by Django 5.2.13 on 2026-07-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0020_placement_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='subject',
            field=models.CharField(blank=True, choices=[('Matematik', 'Matematik'), ('Türkçe', 'Türkçe'), ('Fizik', 'Fizik'), ('Kimya', 'Kimya'), ('Biyoloji', 'Biyoloji'), ('Felsefe', 'Felsefe'), ('Din', 'Din'), ('Tarih', 'Tarih'), ('Coğrafya', 'Coğrafya')], db_index=True, default='', max_length=30, verbose_name='Ders'),
        ),
    ]
